[paths]
# 目标板配置文件路径（支持相对路径，无需绝对路径）
# 如果当前目录找不到，脚本会自动去 user_files/configs 目录下搜索
ccxml = NewTargetConfiguration.ccxml

[firmware]
# Bootloader 固件文件名及烧录地址 (支持通配符 * 自动识别最新版本)
boot = ADM32F036_mc_boot_*.bin
boot_addr = 0x3F6000

# App 固件文件名及烧录地址 (支持通配符 * 自动识别最新版本)
app = ADM32F036_mc_app_*.bin
app_addr = 0x3E8000
